Home/urls.py
from django.urls import path as p
from . import views as v
app_name="Home"

urlpatterns=[
p('',v.index),

]

Personas/urls.py
from django.urls import path

from . import views as v 

app_name="personas"

urlpatterns = [
    #Urls de Clientes
    path("clientes/", v.ClientesIndex.as_view(), name="clientesIndex"),
    path("clientes/nuevo/", v.ClienteCreate.as_view(), name="clientesNuevos"),
    path("clientes/detalles/<pk>/", v.ClienteDetail.as_view(), name="clientesDetalles"),
    path("clientes/actualizar/<pk>/", v.ClienteUpdate.as_view(), name="clientesActualizar"),
    path("clientes/eliminar/<pk>/", v.ClienteDelete.as_view(), name="clientesEliminar"),

    #urls de Proveedores
    path("proveedores/",v.ProveedorList.as_view(),name="proveedores"),
    path("proveedores/nuevo/",v.ProveedorCreate.as_view(),name="proveedoresNuevos"),
    path("proveedores/detalles/<pk>/",v.ProveedorDetail.as_view(),name="proveedoresDetalles"),
    path("proveedores/actualizar/<pk>/",v.ProveedorUpdate.as_view(),name="proveedoresActualizar"),
    path("proveedores/eliminar/<pk>/",v.ProveedorDelete.as_view(),name="proveedoresEliminar"),




]

SIGEVI/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls",namespace="Home")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('inventario/',include("Inventario.urls",namespace="Inventario")),
]

templates/Proveedor/create.html
{% extends 'base/body.html' %}
{% block title %}
    Crear Proveedor
{% endblock title %}
{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Inserción de Proveedor Nuevo</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success" type="submit">Guardar</button>
                <a class="btn btn-danger" href="/personas/proveedores/">Cancelar</a>
            </form>
        </div>
    </div>
{% else %}
{% include 'base/login_info.html' %}
{% endif %}
{% endblock content %}


    

templates/Proveedor/delete.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Proveedores
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Proveedor {{object.razonSocial}}</h1>
            <hr class="dropdown-divider">
        </div>
        {%else%}


    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
    <form method="POST">
		{%csrf_token%}
		<h3>Se van a eliminar los registros de {{object.razonSocial}} identificado con ID {{object.NIT}}, ¿Continuar?</h3>
        <div class="container-fluid">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">NIT</th>
                        <th scope="col">Razón Social</th>
                        <th scope="col">Direccion Principal</th>
                        <th scope="col">Direccion de Punto de Venta</th>
                        <th scope="col">Teléfono</th>     
                        <th scope="col">Correo Electronico</th>      
                    </tr>
                    </thead>
                    <tbody>  
                        <tr>
                            <th scope="row">{{object.NIT}}</th>
                            <td>{{object.razonSocial}}</td>
                            <td>{{object.direccionEmpresa}}</td>
                            <td>{{object.direccionVenta}}</td>
                            <td>{{object.telefono}}</td>
                            <td>{{object.correo}}</td>
                        </tr>
                    </tbody>
            </table>
    </div>    
		    <td><a class="btn btn-info" href="{% url 'personas:proveedoresDetalles' object.NIT %}">Regresar a Detalles</a>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="/personas/proveedores/">Cancelar y Regresar a Listado General</a>
	</form>

    {%else%}

    <p>Inicie Sesión para poder ver estos Datos dando clic<strong><a href="/auth/login"> aquí</a></strong></p>

    {%endif%}

        
{%endblock content%}

templates/Proveedor/details.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Proveedores
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Proveedor {{object.razonSocial}}</h1>
            <hr class="dropdown-divider">
        </div>
    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}

        <div class="container-fluid">
            {%if object%}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">NIT</th>
                    <th scope="col">Razón Social</th>
                    <th scope="col">Direccion Principal</th>
                    <th scope="col">Direccion de Punto de Venta</th>
                    <th scope="col">Teléfono</th>     
                    <th scope="col">Correo Electronico</th>      
                </tr>
                </thead>
                <tbody>  
                    <tr>
                        <th scope="row">{{object.NIT}}</th>
                        <td>{{object.razonSocial}}</td>
                        <td>{{object.direccionEmpresa}}</td>
                        <td>{{object.direccionVenta}}</td>
                        <td>{{object.telefono}}</td>
                        <td>{{object.correo}}</td>
                    </tr>
                </tbody>
            </table>
               
                <a class="btn btn-primary" href="/personas/proveedores/">Atrás</a>
                <a class="btn btn-warning" href="{% url 'personas:proveedoresActualizar' object.NIT %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'personas:proveedoresEliminar' object.NIT %}">Borrar</a>
        {%endif%}
    </div>

    {%else%}

    {% include 'base/login_info.html' %}

    {%endif%}
    
{%endblock content%}

templates/Proveedor/index.html
{% extends "base/body.html" %}

{% block title %}
Listado General de Proveedores
    
{% endblock title %}


{% block header %}
    <h1>Listado General de Proveedores  <a class="btn btn-success" href="{% url 'personas:proveedoresNuevos' %}">Añadir Proveedor nuevo</a></h1>
{% endblock header %}
    

{% block content %}
    {% if query %}
    <div class="container-fluid">
            <div>
                <form method="get">
                <p>Para Buscar un Proveedor en específico, digite su identificacion en la caja de texto y presione el boton buscar <input type="text" name="NIT" > <input type="submit" value="buscar">
                </p>
                </form>
            </div>
        <hr class="dropdown-divider">
    </div>


        <div class="container-fluid">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">NIT</th>
                    <th scope="col">Razón Social</th>
                    
                    <th scope="col">Opciones</th>        
                </tr>
                </thead>
                <tbody>  
                    {% for row in query %}
                    <tr>
                        <th scope="row">{{row.NIT}}</th>
                        <td>{{row.razonSocial}}</td>
                        
                        <td><a class="btn btn-info" href="{% url 'personas:proveedoresDetalles' row.NIT %}">Info</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    {% else %}
    <div class="container-fluid">
        <div>
            <form method="get">
            <p>Para Buscar un Proveedor en específico, digite su identificacion en la caja de texto y presione el boton buscar <input type="text" name="NIT" > <input type="submit" value="buscar">
            </p>
            </form>
        </div>
    <hr class="dropdown-divider">
</div>   
        <p>No hay registros!, Esto puede pasar por dos razones:</p>
        <p>1. No existen coincidencias con los criterios de búsqueda</p>
        <p>2. No existen Registros o no se ṕuede acceder a ellos</p>
        <p>Si sigue viendo esta pantalla y no ha realizado ninguna consulta, contacte al proveedor del software para mayor información</p>
           
    {% endif %}
            

    
{% endblock content %}

templates/Proveedor/update.html
{% extends 'base/body.html' %}



{% block title %}
    Gestión de Proveedores
{% endblock title %}



{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Actualizacion de Proveedor con identificación {{object.NIT}}</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
<div class="container">
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <td><a class="btn btn-info" href="{% url 'personas:proveedoresDetalles' object.NIT %}">Regresar a Detalles</a>
                <button class="btn btn-primary" type="submit">Actualizar</button>
                <a class="btn btn-danger" href="/personas/proveedores/">Cancelar y Regresar a Listado General</a>
            </form>
        </div>
    </div>
{% else %}
<h1>inicie sesion para continuar</h1>
{% endif %}
</div>
{% endblock content %}


    