Gestion/urls.py
from django.urls import path
from . import views as v
app_name="gestion"

urlpatterns = [
    #Gestion de Marcas
    path('marcas/',v.MarcaList.as_view(),name="marcaIndex"),
    path('marcas/nuevo/',v.MarcaCreate.as_view(),name="marcaCrear"),
    path('marcas/actualizar/<pk>/',v.MarcaUpdate.as_view(),name="marcaActualizar"),
    path('marcas/eliminar/<pk>/',v.MarcaDelete.as_view(),name="marcaEliminar"),
     
     #Gestion de Categorías
    path('categoria/',v.CategoriaList.as_view(),name="categoriaIndex"),
    path('categoria/nuevo/',v.CategoriaCreate.as_view(),name="categoriaCrear"),
    path('categoria/actualizar/<pk>/',v.CategoriaUpdate.as_view(),name="categoriaEditar"),
    path('categoria/eliminar/<pk>/',v.CategoriaDelete.as_view(),name="categoriaEliminar"),
    path('categoria/detalles/<pk>/',v.CategoriaDetail,name="categoriaDetalle"),




    
]

Home/urls.py
from django.urls import path as p
from . import views as v
app_name="Home"

urlpatterns=[
p('',v.index),

]

Inventario/urls.py
from django.urls import path 
from . import views as v
app_name="Inventario"
urlpatterns = [
    


    #Gestion de Productos
    path('producto/',v.ProductoList.as_view(),name="productoIndex"),
    path('producto/nuevo/',v.ProductoCreate.as_view(),name="productoCrear"),
    path('producto/detalles/<pk>/',v.ProductoDetail.as_view(),name="productoDetalle"),
    path('producto/actualizar/<pk>/',v.ProductoUpdate.as_view(),name="productoEditar"),
    path('producto/eliminar/<pk>/',v.ProductoDelete.as_view(),name="productoEliminar"),
    path('producto/related/<categoria>/',v.ProductoCategoria,name="productoCategoria"),


    #carrito
    path('agregar/<pk>/',v.agregar_carrito,name="add"),
    path('eliminar/<pk>/',v.eliminar_producto,name="del"),
    path('restar/<pk>/',v.restar_producto,name="remove"),
    path('limpiar/',v.limpiar,name="cls"),
    path('pay/',v.pagar,name="pay"),
    path('PDF/', v.generar_pdf, name="PDF"),

]

SIGEVI/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls",namespace="Home")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('inventario/',include("Inventario.urls",namespace="Inventario")),
]

templates/base/body.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title> 
		{% block title %}   
		{% endblock title %} 

	</title>
	<link rel="stylesheet" href="">
	{% include './header.html' %}
	{% if user.is_authenticated %}
	    {% include './menu.html' %}
	   
	{% endif %}
</head>
<body>
	
		{% block header %}
			
		{% endblock header %}
		
	    {% block content %}
		
		{% endblock content %}
	

	{% include './footer.html' %}
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	<script src="{% static "js/bootstrap.bundle.min.js" %}"></script>
</body>
</html>

templates/base/header.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">SIGEVI</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Personas {% bs_icon 'person' %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="/personas/clientes/">Listar Clientes {% bs_icon 'card-checklist' %}</a></li>
            <li><a class="dropdown-item" href="/personas/clientes/nuevo/">Agregar Cliente Nuevo {% bs_icon 'person-plus' %}</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="/personas/proveedores/">Listar Proveedores {% bs_icon 'card-checklist' %}</a></li>
            <li><a class="dropdown-item" href="/personas/proveedores/nuevo/">Agregar Proveedor Nuevo {% bs_icon 'person-plus' %}</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Inventario {% bs_icon 'book' %}
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="{% url 'gestion:categoriaIndex' %}">Listar Categorías {% bs_icon 'card-checklist' %}</a></li>
            <li><a class="dropdown-item" href="{% url 'gestion:categoriaCrear' %}">Agregar Categoría Nueva {% bs_icon 'clipboard-data' %}</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'gestion:marcaIndex' %}">Listar Marcas {% bs_icon 'card-checklist' %}</a></li>
            <li><a class="dropdown-item" href="{% url 'gestion:marcaCrear' %}">Agregar Marca Nueva {% bs_icon 'clipboard-data' %}</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="{% url 'Inventario:productoIndex' %}">Listar Productos {% bs_icon 'card-checklist' %}</a></li>
            <li><a class="dropdown-item" href="{% url 'Inventario:productoCrear' %}">Agregar Producto Nuevo {% bs_icon 'clipboard-data' %}</a></li>
          </ul>
        </li>
      </ul>
  </div>
  <div class="dropdown">
    <button class="btn btn-warning dropdown-toggle" type="button" id="dropdownMenu2" data-bs-toggle="dropdown" aria-expanded="false">
      Sesión iniciada como {{user.username}}
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu2">
      
      <li><a class="dropdown-item" type="button" href="/auth/logout">Cerrar Sesión{% bs_icon 'power' %}</a></li>
    </ul>
  </div>
</nav>
{% else %}
<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <div class="container-fluid">
    <a class="navbar-brand" >SIGEVI</a>
    <div class="col col-lg-2" aling="right">
      <a class="btn btn-success" href="/auth/login">Iniciar Sesión {% bs_icon 'door-open' %}</a>
    </div>
    </div> 
</nav>    

{% endif %}

templates/base/login_info.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}


    
  <div class="modal" tabindex="-1">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Modal title</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>Modal body text goes here.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

templates/base/menu.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}