Home/urls.py
from django.urls import path as p
from . import views as v
app_name="Home"

urlpatterns=[
p('',v.index),

]

Inventario/urls.py
from django.urls import path 
from . import views as v
app_name="Inventario"
urlpatterns = [
    


    #Gestion de Productos
    path('producto/',v.ProductoList.as_view(),name="productoIndex"),
    path('producto/nuevo/',v.ProductoCreate.as_view(),name="productoCrear"),
    path('producto/detalles/<pk>/',v.ProductoDetail.as_view(),name="productoDetalle"),
    path('producto/actualizar/<pk>/',v.ProductoUpdate.as_view(),name="productoEditar"),
    path('producto/eliminar/<pk>/',v.ProductoDelete.as_view(),name="productoEliminar"),
    path('producto/related/<categoria>/',v.ProductoCategoria,name="productoCategoria"),


    #carrito
    path('agregar/<pk>/',v.agregar_carrito,name="add"),
    path('eliminar/<pk>/',v.eliminar_producto,name="del"),
    path('restar/<pk>/',v.restar_producto,name="remove"),
    path('limpiar/',v.limpiar,name="cls"),
    path('pay/',v.pagar,name="pay"),
    path('PDF/', v.generar_pdf, name="PDF"),

]

SIGEVI/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls",namespace="Home")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('inventario/',include("Inventario.urls",namespace="Inventario")),
]

carrito/models.py
from django.db import models

from Inventario.models import Producto

# Create your models here.
class Carrito(models.Model):
    producto = models.ForeignKey(Producto,on_delete=models.CASCADE)
    cantidad = models.CharField(max_length=10)
    total =  models.CharField(max_length=10)

carrito/views.py
from django.shortcuts import render

# Create your views here.

templates/Producto/carrito.html
{% load static %}
{%load bootstrap5%}
{%bootstrap_css%}
{% load bootstrap_icons %}

<div class="container-fluid">
<h3>Carrito de compras</h3>
         


     {% if request.session.carrito.items %}
         <h5>Total a pagar {{total_carrito}}
         <a href="{% url 'Inventario:pay' %}" class="btn btn-success">Hacer Venta{%bs_icon 'check'%}</a>
         <a href="{% url 'Inventario:PDF' %}" class="btn btn-success">Crear Cotización{%bs_icon 'check'%}</a>
         <a href="{% url 'Inventario:cls' %}" class="btn btn-danger">Eliminar Carrito{%bs_icon 'cart-x'%}</a>
        </h5>
         <h6>Listado de productos</h6>
    <table class="table table-striped table-hover">
     <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Producto</th>
          <th scope="col">Cantidad</th>
          <th scope="col">Precio Unitario</th>
          <th scope="col">Operacion</th>
        </tr>
      </thead>
     <tbody>
     {% for key,value in request.session.carrito.items  %}
        <tr>
          <th scope="row">{{ value.producto_id }}</th>
          <td>{{ value.nombre }}</td>
          <td>{{ value.cantidad }}</td>
          <td>{{ value.precio }}</td>
          <td><a href="{% url 'Inventario:add' value.producto_id %}" class="btn btn-success">+{%bs_icon 'bag-plus'%}</a>
              <a href="{% url 'Inventario:remove' value.producto_id %}" class="btn btn-warning">-{%bs_icon 'bag-dash'%}</a>
          </td>

        </tr>
    {% endfor %}
    </table>

    {% else %}
         <div class="alert alert-primary" role="alert">
             <h6>Añada un elemento al carrito para empezar</h6>
        </div>

    {% endif %}

</div>

templates/Producto/create.html
{% extends 'base/body.html' %}

{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Inserción de Producto Nuevo</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success" type="submit">Guardar</button>
                <a class="btn btn-danger" href="{% url 'Inventario:productoIndex' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% else %}
{% include 'base/login_info.html' %}
{% endif %}
{% endblock content %}


    

templates/Producto/delete.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Productos
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Producto {{object.nombre}} {{object.marca}}</h1>
            <hr class="dropdown-divider">
        </div>
        {%else%}


    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
    <form method="POST">
		{%csrf_token%}
		<h3>Se van a eliminar los registros de {{object.nombre}} {{object.producto}}, ¿Continuar?</h3>
        <div class="container-fluid">
            {%if object%}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio de compra</th>
                    <th scope="col">Proveedor</th>     
                    <th scope="col">Marca</th>    
                </tr>
                </thead>
                <tbody>  
                    <tr>
                        <th scope="row">{{object.id}}</th>
                        <td>{{object.nombre}}</td>
                        <td>{{object.cantidad}}</td>
                        <td>{{object.uniades}}</td>
                        <td>{{object.precio_compra}}</td>
                        <td>{{object.marca}}</td>
                    </tr>
                </tbody>
            </table>
               
        {%endif%}
    </div>
    <td><a class="btn btn-info" href="{% url 'Inventario:productoDetalle' object.id %}">Regresar a Detalles</a>
        <button class="btn btn-danger" type="submit">Eliminar</button>
        <a class="btn btn-primary" href="{% url 'Inventario:productoIndex' %}">Cancelar y Regresar a Listado General</a>
    {%else%}

    <p>Inicie Sesión para poder ver estos Datos dando clic<strong><a href="/auth/login"> aquí</a></strong></p>

    {%endif%}
		   
	</form>

    

        
{%endblock content%}

templates/Producto/details.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Productos
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Producto {{query.nombre}}</h1>
            <hr class="dropdown-divider">
        </div>
    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}

        <div class="container-fluid">
            {%if object%}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio de compra</th>
                    <th scope="col">Proveedor</th>     
                    <th scope="col">Marca</th>    
                </tr>
                </thead>
                <tbody>  
                    <tr>
                        <th scope="row">{{object.id}}</th>
                        <td>{{object.nombre}}</td>
                        <td>{{object.cantidad}}</td>
                        <td>{{object.uniades}}</td>
                        <td>{{object.precio_compra}}</td>
                        {% if row.marca == None %}
                        <td>N/A</td>
                            
                        {% else %}
                        <td>{{row.marca}}</td>
                        {% endif %}
                    </tr>
                </tbody>
            </table>
               
                <a class="btn btn-primary" href="{% url 'Inventario:productoIndex' %}">Atrás</a>
                <a class="btn btn-success" href="{% url 'Inventario:productoCategoria' object.categoria %}">Productos Relacionados</a>
                <a class="btn btn-warning" href="{% url 'Inventario:productoEditar' object.id %}">Editar</a>
                <a class="btn btn-danger" href="{% url 'Inventario:productoEliminar' object.id %}">Borrar</a>
        {%endif%}
    </div>

    {%else%}

    {% include 'base/login_info.html' %}

    {%endif%}
    
{%endblock content%}

templates/Producto/index.html
{% extends "base/body.html" %}

{% block title %}
Productos
    
{% endblock title %}


{% block header %}
    <h1>Listado General de Productos  <a class="btn btn-success" href="{% url 'Inventario:productoCrear' %}">Añadir Producto nuevo</a></h1>
{% endblock header %}
    

{% block content %}
    {% if query %}
    <div class="container-fluid">
            <div>
                <form method="get">
                <p>Para Buscar un Producto en específico, digite su nombre en la caja de texto y presione el boton buscar <input type="text" name="producto" > <input type="submit" value="buscar">
                </p>
                </form>
            </div>
        <hr class="dropdown-divider">
    </div>
<table>
    <td>

            <div class="col-12">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Identificación</th>
                        <th scope="col">Producto</th>
                        <th scope="col">Cantidad</th>
                        <th scope="col">Unidades</th>
                        <th scope="col">Marca</th>
                        <th scope="col">Opciones</th>        
                    </tr>
                    </thead>
                    <tbody>  
                        {% for row in query %}
                        <tr>
                            <th scope="row">{{row.id}}</th>
                            <td>{{row.nombre}}</td>
                            <td>{{row.cantidad}}</td>
                            <td>{{row.uniades}}</td>
                             {% if row.marca == None %}
                            <td>N/A</td>
                                
                            {% else %}
                            <td>{{row.marca}}</td>
                            {% endif %}                   
                            <td><a class="btn btn-info" href="{% url 'Inventario:productoDetalle' row.id %}">Info</a>
                            <a class="btn btn-success" href="{% url 'Inventario:add' row.id %}">Añadir a Carrito</a>

                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
        {% else %}
        <div class="container-fluid">
            <div>
                <form method="get">
                <p>Para Buscar un producto en específico, digite su nombre en la caja de texto y presione el boton buscar <input type="text" name="producto" > <input type="submit" value="buscar">
                </p>
                </form>
            </div>
        <hr class="dropdown-divider">
    </div>   
        <p>No hay registros!, Esto puede pasar por dos razones:</p>
        <p>1. No existen coincidencias con los criterios de búsqueda</p>
        <p>2. No existen Registros o no se ṕuede acceder a ellos</p>
        <p>Si sigue viendo esta pantalla y no ha realizado ninguna consulta, contacte al proveedor del software para mayor información</p>
        {% endif %}
                
</td>
<td>
    
    {% if user.is_authenticated %}
    {% include './carrito.html' %}
        
    {% endif %}
        
</td>
</table>
    
{% endblock content %}

templates/Producto/related.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Categoría
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Productos Relacionados</h1>
            <hr class="dropdown-divider">
        </div>
    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
        
        <div class="container-fluid">
            <h3>Estos son todos los elementos que quizás puedan buscar</h3>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio</th>
                 
                    <th scope="col">Marca</th>    
                </tr>
                </thead>
                <tbody>  
                    
                    {% for row in query1  %}
                    <tr>
                        <th scope="row">{{row.id}}</th>
                        <td>{{row.nombre}}</td>
                        <td>{{row.cantidad}}</td>
                        <td>{{row.precio_compra}}</td>                        
                        {% if row.marca == None %}
                        <td>N/A</td>
                            
                        {% else %}
                        <td>{{row.marca}}</td>
                        {% endif %}
                        <td><a class="btn btn-success" href="{% url 'Inventario:add' row.id %}">Añadir a Carrito</a></td>
                        
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>

    {%else%}

    {% include 'base/login_info.html' %}

    {%endif%}
    
{%endblock content%}

templates/Producto/update.html
{% extends 'base/body.html' %}



{% block title %}
    Gestión de Productos
{% endblock title %}



{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Actualizacion de Producto</h1>
    </div>
    {%else%}
    {%endif%}
{%endblock header%}

{% block content %}
<div class="container">
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <td><a class="btn btn-info" href="#">Regresar a Detalles</a>
                <button class="btn btn-primary" type="submit">Actualizar</button>
                <a class="btn btn-danger" href="#">Cancelar y Regresar a Listado General</a>
            </form>
        </div>
    </div>
{% else %}
<h1>inicie sesion para continuar</h1>
{% endif %}
</div>
{% endblock content %}


    