Gestion/urls.py
from django.urls import path
from . import views as v
app_name="gestion"

urlpatterns = [
    #Gestion de Marcas
    path('marcas/',v.MarcaList.as_view(),name="marcaIndex"),
    path('marcas/nuevo/',v.MarcaCreate.as_view(),name="marcaCrear"),
    path('marcas/actualizar/<pk>/',v.MarcaUpdate.as_view(),name="marcaActualizar"),
    path('marcas/eliminar/<pk>/',v.MarcaDelete.as_view(),name="marcaEliminar"),
     
     #Gestion de Categorías
    path('categoria/',v.CategoriaList.as_view(),name="categoriaIndex"),
    path('categoria/nuevo/',v.CategoriaCreate.as_view(),name="categoriaCrear"),
    path('categoria/actualizar/<pk>/',v.CategoriaUpdate.as_view(),name="categoriaEditar"),
    path('categoria/eliminar/<pk>/',v.CategoriaDelete.as_view(),name="categoriaEliminar"),
    path('categoria/detalles/<pk>/',v.CategoriaDetail,name="categoriaDetalle"),




    
]

Home/urls.py
from django.urls import path as p
from . import views as v
app_name="Home"

urlpatterns=[
p('',v.index),

]

Inventario/urls.py
from django.urls import path 
from . import views as v
app_name="Inventario"
urlpatterns = [
    


    #Gestion de Productos
    path('producto/',v.ProductoList.as_view(),name="productoIndex"),
    path('producto/nuevo/',v.ProductoCreate.as_view(),name="productoCrear"),
    path('producto/detalles/<pk>/',v.ProductoDetail.as_view(),name="productoDetalle"),
    path('producto/actualizar/<pk>/',v.ProductoUpdate.as_view(),name="productoEditar"),
    path('producto/eliminar/<pk>/',v.ProductoDelete.as_view(),name="productoEliminar"),
    path('producto/related/<categoria>/',v.ProductoCategoria,name="productoCategoria"),


    #carrito
    path('agregar/<pk>/',v.agregar_carrito,name="add"),
    path('eliminar/<pk>/',v.eliminar_producto,name="del"),
    path('restar/<pk>/',v.restar_producto,name="remove"),
    path('limpiar/',v.limpiar,name="cls"),
    path('pay/',v.pagar,name="pay"),
    path('PDF/', v.generar_pdf, name="PDF"),

]

SIGEVI/urls.py
from django.contrib import admin
from django.urls import path,include
from Registration import views as v

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',v.register,name="register"),
    path('auth/',include("django.contrib.auth.urls")),
    path('',include("Home.urls",namespace="Home")),
    path('personas/',include("Personas.urls",namespace="personas")),
    path('gestion/',include("Gestion.urls",namespace="gestion")),
    path('inventario/',include("Inventario.urls",namespace="Inventario")),
]

templates/Categoria/create.html
{% extends 'base/body.html' %}

{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Inserción de Categoría Nueva</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-success" type="submit">Guardar</button>
                <a class="btn btn-danger" href="{% url 'gestion:categoriaIndex' %}">Cancelar</a>
            </form>
        </div>
    </div>
{% else %}
{% include 'base/login_info.html' %}
{% endif %}
{% endblock content %}


    

templates/Categoria/delete.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Categorías
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de Categoría {{object.nombre}} </h1>
            <hr class="dropdown-divider">
        </div>
        {%else%}


    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
    <form method="POST">
		{%csrf_token%}
		<h3>Se van a eliminar los registros de {{object.nombre}}, ¿Continuar?</h3>
        <div class="container-fluid">
            {%if object%}
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nombre</th>    
                    </tr>
                    </thead>
                    <tbody>  
                        <tr>
                            <th scope="row">{{object.id}}</th>
                            <td>{{object.nombre}}</td>
                        </tr>
                    </tbody>
            </table>
        {%endif%}
    </div>

    {%else%}

    <p>Inicie Sesión para poder ver estos Datos dando clic<strong><a href="/auth/login"> aquí</a></strong></p>

    {%endif%}
		    <td>
            <button class="btn btn-danger" type="submit">Eliminar</button>
            <a class="btn btn-primary" href="{% url 'gestion:categoriaIndex' %}">Cancelar y Regresar a Listado General</a>
	</form>

    

        
{%endblock content%}

templates/Categoria/details.html
{% extends 'base/body.html' %}


{% block title %}
    Gestión de Categoría
{% endblock title %}


    

{%block header%}
 
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1>Detalles de la Categoría {{query.nombre}}</h1>
            <hr class="dropdown-divider">
        </div>
    {%endif%}
{%endblock header%}

{%block content%}

    {% if user.is_authenticated %}
        
        <div class="container-fluid">
            {%if query1%}
            <h3>Estos son todos los elementos que están contenidos en dicha categoría</h3>
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Nombre</th>
                    <th scope="col">Cantidad</th>
                    <th scope="col">Precio de compra</th>
                    <th scope="col">Proveedor</th>     
                    <th scope="col">Marca</th>    
                </tr>
                </thead>
                <tbody>  
                    
                    {% for row in query1  %}
                    <tr>
                        <th scope="row">{{row.id}}</th>
                        <td>{{row.nombre}}</td>
                        <td>{{row.cantidad}}</td>
                        <td>{{row.uniades}}</td>
                        <td>{{row.precio_compra}}</td>
                        {% if row.marca == None %}
                        <td>N/A</td>
                            
                        {% else %}
                        <td>{{row.marca}}</td>
                        {% endif %}
                        
                        <td> 
                            <a class="btn btn-warning" href="{% url 'Inventario:productoEditar' row.id %}">Editar</a>
                            <a class="btn btn-danger" href="#">Borrar</a></td>
                    </tr>
                    {% endfor %}
                        
                    
                </tbody>
            </table>
               {% else %}
                   <h3>No existen registros</h3>
                   <p>Intente agregar uno haciendo clic en <a class="btn btn-success" href="{% url 'Inventario:productoCrear' %}">Añadir producto</a></p>
               
            {%endif%}
            <a class="btn btn-primary" href="{% url 'gestion:categoriaIndex' %}">Atrás</a>
    </div>

    {%else%}

    {% include 'base/login_info.html' %}

    {%endif%}
    
{%endblock content%}

templates/Categoria/index.html
{% extends "base/body.html" %}

{% block title %}
Categorías
    
{% endblock title %}


{% block header %}
{% if user.is_authenticated %}
    <h1>Listado General de Categorías <a class="btn btn-success" href="{% url 'gestion:categoriaCrear' %}">Agregar Nuevo...</a> </h1>

{% endif %}
    
{% endblock header %}
    

{% block content %}
    {% if query %}
    <div class="container-fluid">
            <div>
                <form method="get">
                <p>Para Buscar una Categoría en específico, digite su nombre en la caja de texto y presione el boton buscar <input type="text" name="categoria" > <input type="submit" value="buscar">
                </p>
                </form>
            </div>
        <hr class="dropdown-divider">
    </div>


        <div class="container-fluid">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Categoría</th>

                    
                    <th scope="col">Opciones</th>        
                </tr>
                </thead>
                <tbody>  
                    {% for row in query %}
                    <tr>
                        <td>{{row.id}}</td>
                        <td>{{row.nombre}}</td>
                        
                        <td><a class="btn btn-info" href="{% url 'gestion:categoriaDetalle' row.id %}">Info
                        <a class="btn btn-warning" href="{% url 'gestion:categoriaEditar' row.id %}">Editar categoría</a>
                        <a class="btn btn-danger" href="{% url 'gestion:categoriaEliminar' row.id %}">Eliminar categoría</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    {% else %}
    <div class="container-fluid">
        <div>
            <form method="get">
            <p>Para Buscar una Categoría en específico, digite su identificacion en la caja de texto y presione el boton buscar <input type="text" name="Categoría" > <input type="submit" value="buscar">
            </p>
            </form>
        </div>
    <hr class="dropdown-divider">
</div>   
        <p>No hay registros!, intente con otra marca o revise que esté bien escrita</p>
            <a class="btn btn-primary" href="{% url 'gestion:marcaIndex' %}">Volver Atrás</a>
    {% endif %}
            

    
{% endblock content %}

templates/Categoria/update.html
{% extends 'base/body.html' %}



{% block title %}
    Gestión de Categorías
{% endblock title %}



{%block header%}
    {% if user.is_authenticated %}
    <div class="container-fluid">
        <h1>Formulario de Actualizacion de Categoría</h1>
    </div>
    {%endif%}
{%endblock header%}

{% block content %}
<div class="container">
{% if user.is_authenticated %}
    {%load crispy_forms_tags%}
    <div class="row justify-content-md-center">
        <div class="col col-lg-8">
            <form method="post">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-primary" type="submit">Actualizar</button>
                <a class="btn btn-danger" href="{% url 'gestion:categoriaIndex' %}">Cancelar y Regresar a Listado General</a>
            </form>
        </div>
    </div>
{% else %}
<h1>inicie sesion para continuar</h1>
{% endif %}
</div>
{% endblock content %}


    